import { spawnSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const isGithubActions = process.env.GITHUB_ACTIONS === 'true';
const isStaticExport = isGithubActions || process.env.STATIC_EXPORT === 'true';

console.log(`[Build] Starting production build (static export: ${isStaticExport})...`);

// 1. Clean previous build outputs
const outDir = path.join(rootDir, 'out');
const distDir = path.join(rootDir, 'dist');
const buildDir = path.join(rootDir, isStaticExport ? '.next' : '.next_build');

if (fs.existsSync(buildDir)) {
  fs.rmSync(buildDir, { recursive: true, force: true });
}
if (fs.existsSync(outDir)) {
  fs.rmSync(outDir, { recursive: true, force: true });
}
if (fs.existsSync(distDir)) {
  fs.rmSync(distDir, { recursive: true, force: true });
}

// 2. Locate Next.js CLI binary
const localDistBin = path.join(rootDir, 'node_modules', 'next', 'dist', 'bin', 'next');
const localDotBin = path.join(rootDir, 'node_modules', '.bin', 'next');

let buildCmd = 'next';
let buildArgs = ['build'];

if (fs.existsSync(localDistBin)) {
  buildCmd = process.execPath;
  buildArgs = [localDistBin, 'build'];
} else if (fs.existsSync(localDotBin)) {
  buildCmd = localDotBin;
  buildArgs = ['build'];
}

console.log(`[Build] Running Next.js build: ${buildCmd} ${buildArgs.join(' ')}`);

const buildEnv = {
  ...process.env,
  NODE_ENV: 'production',
};

// Only override dist dir if NOT doing static export, because Next.js 15 export requires default .next
if (!isStaticExport) {
  buildEnv.NEXT_DIST_DIR = '.next_build';
}

const result = spawnSync(buildCmd, buildArgs, {
  cwd: rootDir,
  stdio: 'inherit',
  env: buildEnv,
});

if (result.status !== 0) {
  console.error(`[Build] Next.js build failed with exit code ${result.status}`);
  if (fs.existsSync(buildDir) && !isStaticExport) {
    fs.rmSync(buildDir, { recursive: true, force: true });
  }
  process.exit(result.status || 1);
}

// 3. Populate standalone artifacts into .next/standalone and .next/static
const targetNextDir = path.join(rootDir, '.next');
const targetStandaloneDir = path.join(targetNextDir, 'standalone');
const targetStaticDir = path.join(targetNextDir, 'static');

const builtStandalone = path.join(buildDir, 'standalone');
const builtStatic = path.join(buildDir, 'static');

if (fs.existsSync(builtStandalone) && builtStandalone !== targetStandaloneDir) {
  console.log(`[Build] Syncing standalone output from ${builtStandalone} to ${targetStandaloneDir}...`);
  if (fs.existsSync(targetStandaloneDir)) {
    fs.rmSync(targetStandaloneDir, { recursive: true, force: true });
  }
  fs.mkdirSync(targetNextDir, { recursive: true });
  fs.cpSync(builtStandalone, targetStandaloneDir, { recursive: true });

  // Next.js standalone requires static and public to be in .next/standalone
  if (fs.existsSync(builtStatic)) {
    const standaloneStatic = path.join(targetStandaloneDir, '.next', 'static');
    fs.mkdirSync(path.dirname(standaloneStatic), { recursive: true });
    fs.cpSync(builtStatic, standaloneStatic, { recursive: true });
  }

  const publicDir = path.join(rootDir, 'public');
  if (fs.existsSync(publicDir)) {
    const standalonePublic = path.join(targetStandaloneDir, 'public');
    fs.cpSync(publicDir, standalonePublic, { recursive: true });
  }
}

if (fs.existsSync(builtStatic) && builtStatic !== targetStaticDir) {
  console.log(`[Build] Syncing static assets from ${builtStatic} to ${targetStaticDir}...`);
  if (!fs.existsSync(targetStaticDir)) {
    fs.mkdirSync(targetStaticDir, { recursive: true });
  }
  fs.cpSync(builtStatic, targetStaticDir, { recursive: true });
}

// 4. Verify static / export output for dist and out
const sourceDir = fs.existsSync(outDir) ? outDir : fs.existsSync(buildDir) ? buildDir : null;
if (!sourceDir) {
  console.error('[Build] Build output directory was not generated by next build.');
  process.exit(1);
}

console.log(`[Build] Syncing artifacts to ${distDir}...`);

// Ensure dist directory exists
if (fs.existsSync(distDir)) {
  fs.rmSync(distDir, { recursive: true, force: true });
}
fs.mkdirSync(distDir, { recursive: true });

// Copy files to dist
if (fs.existsSync(outDir)) {
  fs.cpSync(outDir, distDir, { recursive: true });
} else {
  // If standalone, copy static assets and HTML from server/app into dist
  if (fs.existsSync(builtStatic)) {
    const distStatic = path.join(distDir, '_next', 'static');
    fs.mkdirSync(path.dirname(distStatic), { recursive: true });
    fs.cpSync(builtStatic, distStatic, { recursive: true });
  }
  const builtAppHtml = path.join(buildDir, 'server', 'app');
  if (fs.existsSync(builtAppHtml)) {
    const files = fs.readdirSync(builtAppHtml);
    for (const f of files) {
      if (f.endsWith('.html')) {
        const targetName = f === 'index.html' ? 'index.html' : f;
        fs.copyFileSync(path.join(builtAppHtml, f), path.join(distDir, targetName));
      }
    }
  }
}

// If public folder exists, ensure all public assets are copied into both out and dist
const publicDir = path.join(rootDir, 'public');
if (fs.existsSync(publicDir)) {
  fs.cpSync(publicDir, distDir, { recursive: true });
  if (fs.existsSync(outDir)) {
    fs.cpSync(publicDir, outDir, { recursive: true });
  }
}

// Create .nojekyll in both dist and out to prevent static hosts (like GitHub Pages) from ignoring _next
fs.writeFileSync(path.join(distDir, '.nojekyll'), '');
if (fs.existsSync(outDir)) {
  fs.writeFileSync(path.join(outDir, '.nojekyll'), '');
}

// 5. Validate output artifacts
if (fs.existsSync(targetStandaloneDir)) {
  const standaloneServer = path.join(targetStandaloneDir, 'server.js');
  if (!fs.existsSync(standaloneServer)) {
    console.warn('[Build] Warning: server.js not found in .next/standalone');
  } else {
    console.log('[Build] Successfully validated .next/standalone/server.js');
  }
}

const distIndex = path.join(distDir, 'index.html');
if (fs.existsSync(distIndex)) {
  console.log(`[Build] Successfully verified dist/index.html (${fs.statSync(distIndex).size} bytes).`);
}

if (fs.existsSync(outDir)) {
  const outIndex = path.join(outDir, 'index.html');
  if (fs.existsSync(outIndex)) {
    console.log(`[Build] Successfully verified out/index.html (${fs.statSync(outIndex).size} bytes).`);
  }
}

// Clean up temporary build directory only when not static export
if (fs.existsSync(buildDir) && !isStaticExport) {
  fs.rmSync(buildDir, { recursive: true, force: true });
}

console.log('[Build] Build completed successfully.');
